// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openflt/fltbase/ent/airport"
	"github.com/openflt/fltbase/ent/city"
	"github.com/openflt/fltbase/ent/predicate"
	"github.com/openflt/fltbase/ent/state"
)

// StateQuery is the builder for querying State entities.
type StateQuery struct {
	config
	ctx               *QueryContext
	order             []state.OrderOption
	inters            []Interceptor
	predicates        []predicate.State
	withCities        *CityQuery
	withAirports      *AirportQuery
	modifiers         []func(*sql.Selector)
	loadTotal         []func(context.Context, []*State) error
	withNamedCities   map[string]*CityQuery
	withNamedAirports map[string]*AirportQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StateQuery builder.
func (sq *StateQuery) Where(ps ...predicate.State) *StateQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *StateQuery) Limit(limit int) *StateQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *StateQuery) Offset(offset int) *StateQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *StateQuery) Unique(unique bool) *StateQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *StateQuery) Order(o ...state.OrderOption) *StateQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryCities chains the current query on the "cities" edge.
func (sq *StateQuery) QueryCities() *CityQuery {
	query := (&CityClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(state.Table, state.FieldID, selector),
			sqlgraph.To(city.Table, city.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, state.CitiesTable, state.CitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAirports chains the current query on the "airports" edge.
func (sq *StateQuery) QueryAirports() *AirportQuery {
	query := (&AirportClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(state.Table, state.FieldID, selector),
			sqlgraph.To(airport.Table, airport.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, state.AirportsTable, state.AirportsColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first State entity from the query.
// Returns a *NotFoundError when no State was found.
func (sq *StateQuery) First(ctx context.Context) (*State, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{state.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *StateQuery) FirstX(ctx context.Context) *State {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first State ID from the query.
// Returns a *NotFoundError when no State ID was found.
func (sq *StateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{state.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *StateQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single State entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one State entity is found.
// Returns a *NotFoundError when no State entities are found.
func (sq *StateQuery) Only(ctx context.Context) (*State, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{state.Label}
	default:
		return nil, &NotSingularError{state.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *StateQuery) OnlyX(ctx context.Context) *State {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only State ID in the query.
// Returns a *NotSingularError when more than one State ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *StateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{state.Label}
	default:
		err = &NotSingularError{state.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *StateQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of States.
func (sq *StateQuery) All(ctx context.Context) ([]*State, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*State, *StateQuery]()
	return withInterceptors[[]*State](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *StateQuery) AllX(ctx context.Context) []*State {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of State IDs.
func (sq *StateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err = sq.Select(state.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *StateQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *StateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*StateQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *StateQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *StateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *StateQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *StateQuery) Clone() *StateQuery {
	if sq == nil {
		return nil
	}
	return &StateQuery{
		config:       sq.config,
		ctx:          sq.ctx.Clone(),
		order:        append([]state.OrderOption{}, sq.order...),
		inters:       append([]Interceptor{}, sq.inters...),
		predicates:   append([]predicate.State{}, sq.predicates...),
		withCities:   sq.withCities.Clone(),
		withAirports: sq.withAirports.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithCities tells the query-builder to eager-load the nodes that are connected to
// the "cities" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *StateQuery) WithCities(opts ...func(*CityQuery)) *StateQuery {
	query := (&CityClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withCities = query
	return sq
}

// WithAirports tells the query-builder to eager-load the nodes that are connected to
// the "airports" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *StateQuery) WithAirports(opts ...func(*AirportQuery)) *StateQuery {
	query := (&AirportClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withAirports = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.State.Query().
//		GroupBy(state.FieldCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *StateQuery) GroupBy(field string, fields ...string) *StateGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StateGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = state.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//	}
//
//	client.State.Query().
//		Select(state.FieldCode).
//		Scan(ctx, &v)
func (sq *StateQuery) Select(fields ...string) *StateSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &StateSelect{StateQuery: sq}
	sbuild.label = state.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StateSelect configured with the given aggregations.
func (sq *StateQuery) Aggregate(fns ...AggregateFunc) *StateSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *StateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !state.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *StateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*State, error) {
	var (
		nodes       = []*State{}
		_spec       = sq.querySpec()
		loadedTypes = [2]bool{
			sq.withCities != nil,
			sq.withAirports != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*State).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &State{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withCities; query != nil {
		if err := sq.loadCities(ctx, query, nodes,
			func(n *State) { n.Edges.Cities = []*City{} },
			func(n *State, e *City) { n.Edges.Cities = append(n.Edges.Cities, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withAirports; query != nil {
		if err := sq.loadAirports(ctx, query, nodes,
			func(n *State) { n.Edges.Airports = []*Airport{} },
			func(n *State, e *Airport) { n.Edges.Airports = append(n.Edges.Airports, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range sq.withNamedCities {
		if err := sq.loadCities(ctx, query, nodes,
			func(n *State) { n.appendNamedCities(name) },
			func(n *State, e *City) { n.appendNamedCities(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range sq.withNamedAirports {
		if err := sq.loadAirports(ctx, query, nodes,
			func(n *State) { n.appendNamedAirports(name) },
			func(n *State, e *Airport) { n.appendNamedAirports(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range sq.loadTotal {
		if err := sq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *StateQuery) loadCities(ctx context.Context, query *CityQuery, nodes []*State, init func(*State), assign func(*State, *City)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*State)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.City(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(state.CitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.state_cities
		if fk == nil {
			return fmt.Errorf(`foreign-key "state_cities" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "state_cities" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *StateQuery) loadAirports(ctx context.Context, query *AirportQuery, nodes []*State, init func(*State), assign func(*State, *Airport)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*State)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Airport(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(state.AirportsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.state_airports
		if fk == nil {
			return fmt.Errorf(`foreign-key "state_airports" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "state_airports" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sq *StateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *StateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(state.Table, state.Columns, sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, state.FieldID)
		for i := range fields {
			if fields[i] != state.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *StateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(state.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = state.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCities tells the query-builder to eager-load the nodes that are connected to the "cities"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (sq *StateQuery) WithNamedCities(name string, opts ...func(*CityQuery)) *StateQuery {
	query := (&CityClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if sq.withNamedCities == nil {
		sq.withNamedCities = make(map[string]*CityQuery)
	}
	sq.withNamedCities[name] = query
	return sq
}

// WithNamedAirports tells the query-builder to eager-load the nodes that are connected to the "airports"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (sq *StateQuery) WithNamedAirports(name string, opts ...func(*AirportQuery)) *StateQuery {
	query := (&AirportClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if sq.withNamedAirports == nil {
		sq.withNamedAirports = make(map[string]*AirportQuery)
	}
	sq.withNamedAirports[name] = query
	return sq
}

// StateGroupBy is the group-by builder for State entities.
type StateGroupBy struct {
	selector
	build *StateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *StateGroupBy) Aggregate(fns ...AggregateFunc) *StateGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *StateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StateQuery, *StateGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *StateGroupBy) sqlScan(ctx context.Context, root *StateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StateSelect is the builder for selecting fields of State entities.
type StateSelect struct {
	*StateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *StateSelect) Aggregate(fns ...AggregateFunc) *StateSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *StateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StateQuery, *StateSelect](ctx, ss.StateQuery, ss, ss.inters, v)
}

func (ss *StateSelect) sqlScan(ctx context.Context, root *StateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
