// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openflt/fltbase/ent/airport"
	"github.com/openflt/fltbase/ent/city"
	"github.com/openflt/fltbase/ent/state"
)

// StateCreate is the builder for creating a State entity.
type StateCreate struct {
	config
	mutation *StateMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (sc *StateCreate) SetCode(s string) *StateCreate {
	sc.mutation.SetCode(s)
	return sc
}

// SetName sets the "name" field.
func (sc *StateCreate) SetName(s string) *StateCreate {
	sc.mutation.SetName(s)
	return sc
}

// AddCityIDs adds the "cities" edge to the City entity by IDs.
func (sc *StateCreate) AddCityIDs(ids ...int) *StateCreate {
	sc.mutation.AddCityIDs(ids...)
	return sc
}

// AddCities adds the "cities" edges to the City entity.
func (sc *StateCreate) AddCities(c ...*City) *StateCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return sc.AddCityIDs(ids...)
}

// AddAirportIDs adds the "airports" edge to the Airport entity by IDs.
func (sc *StateCreate) AddAirportIDs(ids ...int) *StateCreate {
	sc.mutation.AddAirportIDs(ids...)
	return sc
}

// AddAirports adds the "airports" edges to the Airport entity.
func (sc *StateCreate) AddAirports(a ...*Airport) *StateCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return sc.AddAirportIDs(ids...)
}

// Mutation returns the StateMutation object of the builder.
func (sc *StateCreate) Mutation() *StateMutation {
	return sc.mutation
}

// Save creates the State in the database.
func (sc *StateCreate) Save(ctx context.Context) (*State, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StateCreate) SaveX(ctx context.Context) *State {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StateCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StateCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StateCreate) check() error {
	if _, ok := sc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "State.code"`)}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "State.name"`)}
	}
	return nil
}

func (sc *StateCreate) sqlSave(ctx context.Context) (*State, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StateCreate) createSpec() (*State, *sqlgraph.CreateSpec) {
	var (
		_node = &State{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(state.Table, sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Code(); ok {
		_spec.SetField(state.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(state.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := sc.mutation.CitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   state.CitiesTable,
			Columns: []string{state.CitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.AirportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   state.AirportsTable,
			Columns: []string{state.AirportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StateCreateBulk is the builder for creating many State entities in bulk.
type StateCreateBulk struct {
	config
	builders []*StateCreate
}

// Save creates the State entities in the database.
func (scb *StateCreateBulk) Save(ctx context.Context) ([]*State, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*State, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StateCreateBulk) SaveX(ctx context.Context) []*State {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StateCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StateCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
