// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Airport is the predicate function for airport builders.
type Airport func(*sql.Selector)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Region is the predicate function for region builders.
type Region func(*sql.Selector)

// State is the predicate function for state builders.
type State func(*sql.Selector)
